cs412/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('quotes/', include("quotes.urls")),
    path('formdata/', include("formdata.urls")),
    path('restaurant/', include('restaurant.urls')),
    path('blog/', include("blog.urls")),
    path('mini_insta/', include("mini_insta.urls")),
] 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hw/urls.py
## create file: hw/urls.py
 
 
from django.urls import path
from django.conf import settings
from . import views
 
from django.conf.urls.static import static    ## add for static files
urlpatterns = [ 
    # path(r'', views.home, name="home"),
    path(r'', views.home_page, name="home"),
    path(r'about', views.about, name="about"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mini_insta/urls.py
# File: urls.py
# Author: Jocelyn Chan (jchan042@bu.edu) 2/12/2026
# Description: Define which views to display for which URLs

from django.urls import path
from .views import *

urlpatterns = [
    path('', ProfileListView.as_view(), name="show_all_profiles"),
    path('show_all_profiles', ProfileListView.as_view(), name="show_all_profiles"),
    path('profile/<int:pk>', ProfileDetailView.as_view(), name="profile"),
    path('post/<int:pk>', PostDetailView.as_view(), name="post"),
    path('profile/<int:pk>/create_post', CreatePostView.as_view(), name="create_post"),
    path('profile/<int:pk>/update', UpdateProfileView.as_view(), name="update"),
    path('post/<int:pk>/delete', DeletePostView.as_view(), name="delete_post"),
    path('post/<int:pk>/update', UpdatePostView.as_view(), name="update_post"),
    path('profile/<int:pk>/followers', ShowFollowersDetailView.as_view(), name="followers"),
    path('profile/<int:pk>/following', ShowFollowingDetailView.as_view(), name="following"),
    path('profile/<int:pk>/feed', PostFeedListView.as_view(), name="feed"),
    path('profile/<int:pk>/search', SearchView.as_view(), name="search"),
]

mini_insta/models.py
# File: models.py
# Author: Jocelyn Chan (jchan042@bu.edu) 2/10/2026
# Description: Used to define the DB structure/schema

from django.db import models
from django.urls import reverse

# Create your models here.

# Profile model for a user's profile 
class Profile(models.Model): 
    '''Encapsulate the data of an Insta Profile'''
    
    # all the attributes of the profile model
    username = models.TextField(blank=True)
    display_name = models.TextField(blank=True)
    profile_image_url = models.URLField(blank=True)
    bio_text = models.TextField(blank=True)
    join_date = models.DateTimeField(auto_now=True)
    
    # implement string representation
    def __str__(self):
        '''Return a string representation for this model instance'''
        return f'{self.username} profile'    
    
    # accessor method to find and return all posts for a given profile 
    def get_all_posts(self):
        '''Return a QuerySet of posts about this profile'''
    
        return Post.objects.filter(profile=self).order_by('timestamp')
    
    # accessor method to get a list of followers
    def get_followers(self):
        '''Return a list of Profiles who follow this profile'''
        return [f.follower_profile for f in Follow.objects.filter(profile=self)]
    
    # accesor method fo getting the number of followers
    def get_num_followers(self):
        '''Return the count of followers'''
        return len(self.get_followers())
    
    # accessor method to get a list of following 
    def get_following(self):
        '''Return a list of Profiles that this profile follows'''
        return [f.profile for f in Follow.objects.filter(follower_profile=self)]
    
    # accessor method to get the number of following 
    def get_num_following(self):
        '''Return the count of profiles being followed'''
        return len(self.get_following())
    
    # accessor method to get the post feed for this profile
    def get_post_feed(self):
        '''Return a list of Posts from all profiles that this profile follows, most recent first'''
        # get all profiles that this profile follows
        following = self.get_following()
        # get all posts from those profiles, ordered by most recent first
        return Post.objects.filter(profile__in=following).order_by('-timestamp')

    # redirect user to this URL 
    def get_absolute_url(self):
        '''Return the URL to display this profile'''
        return reverse('profile', kwargs={'pk': self.pk})
    
# Post model for a user's profile 
class Post(models.Model):
    '''Encapsulate the data of a person's Instagram post'''
    
    # all the attributes of the post model
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now=True)
    caption = models.TextField(blank=True)
    
    # implement string representation
    def __str__(self):
        '''Return a string representation for this model instance'''
        return f'{self.profile} post {self.pk}'
    
    # accessor method to find and return all photos for a given post 
    def get_all_photos(self):
        '''Return a QuerySet of photos about this post'''
        return Photo.objects.filter(post=self).order_by('timestamp')
    
    # accessor methond to find and return the correct url for the post
    def get_absolute_url(self):
        '''Return the URL to display this post'''
        return reverse('post', kwargs={'pk': self.pk})
    
    # accessor method to find and return all comments for a given post
    def get_all_comments(self):
        '''Return a QuerySet of comments on this post'''
        return Comment.objects.filter(post=self).order_by('timestamp')
    
    # accessor method to find and return all likes for a given post
    def get_likes(self):
        '''Return a QuerySet of likes on this post'''
        return Like.objects.filter(post=self)
    
class Photo(models.Model):
    '''Encapsulate the data of an Insta Photo for a post'''
    
    # all the attributes of the post model
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    image_url = models.URLField(blank=True)
    timestamp = models.DateTimeField(auto_now=True)
    image_file = models.ImageField(blank=True)
    
    # implement string representation
    def __str__(self):
        '''Return a string representation for this model instance'''
        return f'{self.post.profile} post {self.post.pk} photo {self.pk} - {self.get_image_url()}'
    
    # accessor method to return the URL for an image
    def get_image_url(self): 
        '''Return the URL for an image'''
        
        # conditional to see if the image url attribute exists 
        if self.image_file:
            return self.image_file.url
        return self.image_url
    
class Follow(models.Model):
    '''Encapsulate the data of a Follow relationship between two Profiles'''
    
    # the profile being followed 
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="profile")
    
    # the profile doing the following 
    follower_profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="follower_profile")
    timestamp = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        '''Return a string representation of this Follow relationship'''
        return f'{self.follower_profile.username} follows {self.profile.username}'
    
class Comment(models.Model):
    '''Encapsulate the data of a Comment on a Post'''
    
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now=True)
    text = models.TextField(blank=False)
    
    def __str__(self):
        '''Return a string representation of this Comment'''
        # first 50 chars
        return f'@{self.profile.username} on post {self.post.pk}: "{self.text[:50]}"'
    
    
class Like(models.Model):
    '''Encapsulate the data of a Like on a Post'''
    
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        '''Return a string representation of this Like'''
        return f'@{self.profile.username} likes post {self.post.pk}'

mini_insta/forms.py
# File: forms.py
# Author: Jocelyn Chan (jchan042@bu.edu) 2/12/2026
# Description: The form to create a post 

from django import forms
from .models import *

# Form to create a post
class CreatePostForm(forms.ModelForm):
    '''A form to add a Post to the database'''
    
    class Meta:
        '''Associate this form with a Post model from our db'''
        
        model = Post
        fields = ['caption']
        
# Form to update a profile 
class UpdateProfileForm(forms.ModelForm):
    '''A form to change and update an existing profile'''
    
    class Meta:
        '''Associate this form with a Profile model from our DB'''
        
        model = Profile
        fields = ['display_name', 'profile_image_url', 'bio_text']

mini_insta/views.py
# File: urls.py
# Author: Jocelyn Chan (jchan042@bu.edu) 2/12/2026
# Description: Returns an HTML template view for each URL 

from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Profile, Post, Photo
from .forms import CreatePostForm, UpdateProfileForm
from django.urls import reverse

# Create your views here.

# View for all profiles
class ProfileListView(ListView):
    '''Define a view class to show all Instagram Profiles'''
    
    model = Profile
    template_name = "mini_insta/show_all_profiles.html"  # fixed path
    context_object_name = "profiles"  # plural
    
# View for one single profile 
class ProfileDetailView(DetailView):
    '''Define a view class to show a single profile'''
    
    model = Profile 
    template_name = "mini_insta/show_profile.html"
    context_object_name = "profile" # singular 
    
# View for the details of one post
class PostDetailView(DetailView):
    '''Define a view class to show the contents of a single post'''
    
    model = Post
    template_name = "mini_insta/show_post.html"
    context_object_name = "post"
    
# View for creating a new Post
class CreatePostView(CreateView):
    '''Define a view class to handle creating a new post'''
    
    model = Post
    form_class = CreatePostForm
    template_name = "mini_insta/create_post_form.html"
    
    def get_context_data(self, **kwargs):
        '''Add the profile to the context so the template can use it'''
        context = super().get_context_data(**kwargs)
        profile = Profile.objects.get(pk=self.kwargs['pk'])
        context['profile'] = profile
        return context
    
    def form_valid(self, form):
        '''Attach the profile and photo before saving the post'''
        # find the profile using the pk from the URL
        profile = Profile.objects.get(pk=self.kwargs['pk'])
        # attach the profile to the post
        form.instance.profile = profile
        # save the post
        post = form.save()
        
        # read data for files
        files = self.request.FILES.getlist('upload-photos')
        
        # loop through each file and create a Photo object
        for file in files:
            Photo.objects.create(post=post, image_file=file)
            
        return super().form_valid(form)           
        
        # create the photo using the image_url from the form
        # image_url = self.request.POST.get('image_url')
        # if image_url:
        #     Photo.objects.create(post=post, image_url=image_url)
        
# View for updating a user's profile 
class UpdateProfileView(UpdateView):
    model = Profile 
    form_class = UpdateProfileForm
    template_name = "mini_insta/update_profile_form.html"
    
    def get_context_data(self, **kwargs):
        '''Add the profile to the context so the template can use it'''
        context = super().get_context_data(**kwargs)
        profile = Profile.objects.get(pk=self.kwargs['pk'])
        context['profile'] = profile
        return context
    
# View for deleting a post
class DeletePostView(DeleteView):
    '''Define a view class to handle deleting a post'''
    
    model = Post
    template_name = "mini_insta/delete_post_form.html"
    
    def get_context_data(self, **kwargs):
        '''Add the post and profile to the context so the template can use them'''
        context = super().get_context_data(**kwargs)
        post = Post.objects.get(pk=self.kwargs['pk'])
        context['post'] = post
        context['profile'] = post.profile
        return context
    
    def get_success_url(self):
        '''Redirect to the profile page after a successful delete'''
        return reverse('profile', kwargs={'pk': self.object.profile.pk})
    
# View for updating a post
class UpdatePostView(UpdateView):
    '''Define a view class to handle updating a post caption'''
    model = Post
    fields = ['caption']
    template_name = "mini_insta/update_post_form.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = Post.objects.get(pk=self.kwargs['pk'])
        context['post'] = post
        context['profile'] = post.profile
        return context
    
# View for showing a profile's followers
class ShowFollowersDetailView(DetailView):
    '''Define a view class to show all followers of a profile'''
    model = Profile
    template_name = "mini_insta/show_followers.html"
    context_object_name = "profile"

# View for showing who a profile is following
class ShowFollowingDetailView(DetailView):
    '''Define a view class to show all profiles that a profile follows'''
    model = Profile
    template_name = "mini_insta/show_following.html"
    context_object_name = "profile"
    
# View for the post feed
class PostFeedListView(ListView):
    '''Define a view class to show the post feed for a profile'''
    model = Post
    template_name = "mini_insta/show_feed.html"
    context_object_name = "posts"

    def get_queryset(self):
        '''Return the post feed for this profile'''
        profile = Profile.objects.get(pk=self.kwargs['pk'])
        return profile.get_post_feed()

    def get_context_data(self, **kwargs):
        '''Add the profile to the context'''
        context = super().get_context_data(**kwargs)
        profile = Profile.objects.get(pk=self.kwargs['pk'])
        context['profile'] = profile
        return context
    
# View for searching profiles and posts
class SearchView(ListView):
    '''Define a view class to handle searching profiles and posts'''
    model = Profile
    template_name = "mini_insta/search_results.html"
    context_object_name = "profiles"

    def get_queryset(self):
        '''Return profiles matching the search query'''
        query = self.request.GET.get('query', '')
        if query:
            return Profile.objects.filter(username__icontains=query) |                    Profile.objects.filter(display_name__icontains=query) |                    Profile.objects.filter(bio_text__icontains=query)
        return Profile.objects.none()

    def get_context_data(self, **kwargs):
        '''Add profile, query, and matching posts to context'''
        context = super().get_context_data(**kwargs)
        query = self.request.GET.get('query', '')
        profile = Profile.objects.get(pk=self.kwargs['pk'])
        context['profile'] = profile
        context['query'] = query
        if query:
            context['posts'] = Post.objects.filter(caption__icontains=query)
        else:
            context['posts'] = Post.objects.none()
        return context

mini_insta/templates/mini_insta/base.html
<!-- 
File: base.html
Author: Jocelyn Chan (jchan042@bu.edu) 2/12/2026
Description: A base template that other pages can build off upon
 -->

{% load static %}
<html>
    <head>
        <title>Mini Instagram</title>
        <link rel="stylesheet" href="{% static 'mini_insta.css' %}">
    </head>

    <body>
        <!--Header-->
        <header>
            <h1>Mini Instagram</h1>
        </header>
        
        <!--Content other pages insert-->
        {% block content %}
        {% endblock %}

        <!--Footer-->
        <footer>
            <nav>
                <ul>
                    <!-- Home: links to feed if profile exists, else all profiles -->
                    {% if profile %}
                        <li><a href="{% url 'feed' profile.pk %}"><img src="https://cdn-icons-png.flaticon.com/512/5974/5974907.png" alt="Home Button"></a></li>
                    {% else %}
                        <li><a href="{% url 'show_all_profiles' %}"><img src="https://cdn-icons-png.flaticon.com/512/5974/5974907.png" alt="Home Button"></a></li>
                    {% endif %}

                    <!-- Create post button -->
                    {% if profile %}
                        <li><a href="{% url 'create_post' profile.pk %}"><img src="https://www.pngmart.com/files/21/Add-Button-PNG.png" alt="Add a post button"></a></li>
                    {% endif %}

                    <!-- Search link -->
                    {% if profile %}
                        <li><a href="{% url 'search' profile.pk %}"><img src="https://cdn-icons-png.flaticon.com/512/622/622669.png" alt="Search Button"></a></li>
                    {% endif %}

                    <!-- Profile link -->
                    {% if profile %}
                        <li><a href="{% url 'profile' profile.pk %}"><img src="https://cdn-icons-png.flaticon.com/512/1077/1077063.png" alt="Profile Button"></a></li>
                    {% endif %}
                </ul>
            </nav>
        </footer>
    </body>
</html>

mini_insta/templates/mini_insta/create_post_form.html
<!-- 
File: create_post_form.html
Author: Jocelyn Chan (jchan042@bu.edu) 2/12/2026
Description: Form to create a post 
 -->

{% extends 'mini_insta/base.html' %}

{% block content %}

<h2>Create a New Post</h2>

<div class="form-container">
    <form action="{% url 'create_post' profile.pk %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <!-- Upload images -->
         <div class="form-buttons">
            <input type="file" name="upload-photos" id="upload-photos" multiple>
         </div>


         <br>
        <!-- Caption field -->
        <div class="form-field">
            <label for="caption">Caption:</label>
            {{ form.caption }}
        </div>

        <!-- Image URL field -->
        <!-- <div class="form-field">
            <label for="image_url">Image URL:</label>
            <input type="url" name="image_url" id="image_url" placeholder="Paste an image URL here">
        </div> -->

        <!-- Buttons -->
        <div class="form-buttons">
            <input type="submit" value="Post">
            <a href="{% url 'profile' profile.pk %}">
                <button type="button">Cancel</button>
            </a>
        </div>

    </form>
</div>

{% endblock %}

mini_insta/templates/mini_insta/delete_post_form.html
<!-- 
File: delete_post_form.html
Author: Jocelyn Chan (jchan042@bu.edu) 3/01/2026
Description: The page to display the contents of deleting a post
-->

{% extends 'mini_insta/base.html' %}

{% block content %}

<h2>Delete @{{ profile.username }}'s Post</h2>

<div class="post-detail-container">

    <!-- Show the post that's being deleted -->
    <div class="post-left">
        <div class="post-photos">
            {% for photo in post.get_all_photos %}
                <img src="{{ photo.get_image_url }}" alt="Post photo">
            {% empty %}
                <img src="https://png.pngtree.com/png-vector/20221125/ourmid/pngtree-no-image-available-icon-flatvector-illustration-thumbnail-graphic-illustration-vector-png-image_40966590.jpg"
                alt="No image available">
            {% endfor %}
        </div>
    </div>

    <div class="post-right">
        <div class="post-info">
            <p class="post-caption"><b>@{{ profile.username }}: </b>{{ post.caption }}</p>
            <small class="post-timestamp">{{ post.timestamp }}</small>
        </div>

        <hr>

        <p>Are you sure you want to delete this post? This cannot be undone.</p>

        <!-- Confirm deletion via POST to the same delete URL -->
        <div class="form-buttons">
            <form action="{% url 'delete_post' post.pk %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="Delete">
            </form>

            <!-- Confirm cancellation via GET back to profile page -->
            <form action="{% url 'profile' profile.pk %}" method="GET">
                <input type="submit" value="Cancel">
            </form>
        </div>

    </div>
</div>

{% endblock %}

mini_insta/templates/mini_insta/search.html
<!-- 
File: search.html
Author: Jocelyn Chan (jchan042@bu.edu) 3/01/2026
Description: Search page for profiles and posts
-->

{% extends 'mini_insta/base.html' %}

{% block content %}

<h2>Search</h2>

<div class="form-container">
    <form action="{% url 'search' profile.pk %}" method="GET">

        <div class="form-field">
            <label for="query"><strong>Search Profiles & Posts</strong></label>
            <input type="text" name="query" id="query" placeholder="Search by username, name, or caption..."value="{{ query }}">
        </div>

        <div class="form-buttons">
            <input type="submit" value="Search">
            <a href="{% url 'profile' profile.pk %}">
                <button type="button">Cancel</button>
            </a>
        </div>

    </form>
</div>

{% endblock %}

mini_insta/templates/mini_insta/search_results.html
<!-- 
File: search_results.html
Author: Jocelyn Chan (jchan042@bu.edu) 3/01/2026
Description: Search results page for profiles and posts
-->

{% extends 'mini_insta/base.html' %}

{% block content %}

<h2>Search Results for "{{ query }}"</h2>

<div class="form-container">
    <!-- Search form stays at the top so user can refine -->
    <form action="{% url 'search' profile.pk %}" method="GET">
        <div class="form-field">
            <label for="query"><strong>Search Profiles & Posts</strong></label>
            <input type="text" 
                   name="query" 
                   id="query" 
                   placeholder="Search by username, name, or caption..."
                   value="{{ query }}">
        </div>
        <div class="form-buttons">
            <input type="submit" value="Search">
            <a href="{% url 'profile' profile.pk %}">
                <button type="button">Cancel</button>
            </a>
        </div>
    </form>
</div>

<!-- Profile results -->
<div class="search-section">
    <h3 class="search-section-title">Profiles</h3>
    <div class="grid">
        {% for result in profiles %}
            <a href="{% url 'profile' result.pk %}">
                <div class="profile-item">
                    <img src="{{ result.profile_image_url }}" alt="{{ result.username }}'s profile picture">
                    <h3>@{{ result.username }}</h3>
                    <p>{{ result.display_name }}</p>
                </div>
            </a>
        {% empty %}
            <p class="search-empty">No profiles found matching "{{ query }}".</p>
        {% endfor %}
    </div>
</div>

<!-- Post results -->
<div class="search-section">
    <h3 class="search-section-title">Posts</h3>
    <div class="posts-grid">
        {% for post in posts %}
            <a href="{% url 'post' post.pk %}">
                <div class="post-item">
                    {% with photos=post.get_all_photos %}
                        {% if photos %}
                            <img src="{{ photos.first.get_image_url }}" alt="Post photo">
                        {% else %}
                            <img src="https://png.pngtree.com/png-vector/20221125/ourmid/pngtree-no-image-available-icon-flatvector-illustration-thumbnail-graphic-illustration-vector-png-image_40966590.jpg"
                            alt="No image available">
                        {% endif %}
                    {% endwith %}
                </div>
            </a>
            <p class="search-post-caption"><b>@{{ post.profile.username }}:</b> {{ post.caption }}</p>
        {% empty %}
            <p class="search-empty">No posts found matching "{{ query }}".</p>
        {% endfor %}
    </div>
</div>

{% endblock %}

mini_insta/templates/mini_insta/show_all_profiles.html
<!-- 
File: show_all_profiles.html
Author: Jocelyn Chan (jchan042@bu.edu) 2/12/2026
Description: The page to display all of the instagram profiles 
 -->

{% extends 'mini_insta/base.html' %}

{% block content %}

<h2>All Profiles</h2>

<!-- start main -->
<main>
    <div class="grid">
        <!-- Loop to display all profiles -->
        {% for profile in profiles %}
        <!-- Make the whole div clickable -->
        <a href="{% url 'profile' profile.pk %}">
            <div class="profile-item">
                <img src="{{ profile.profile_image_url }}" alt="{{ profile.username }}'s profile picture">
                <h3>@{{ profile.username }}</h3>
                <p>{{ profile.display_name }}</p>
            </div>
        </a>
        
        {% endfor %}
        <!-- End for loop -->
    </div>
</main>

{% endblock %}

mini_insta/templates/mini_insta/show_feed.html
<!-- 
File: show_feed.html
Author: Jocelyn Chan (jchan042@bu.edu) 3/01/2026
Description: The post feed for a profile
-->

{% extends 'mini_insta/base.html' %}

{% block content %}

<h2>@{{ profile.username }}'s Feed</h2>

<div class="feed-container">
    <a href="{% url 'profile' profile.pk %}" class="back-link">Back to @{{ profile.username }}'s Profile</a>


    {% for post in posts %}
    <div class="feed-post">

        <!-- Post header: profile picture and username -->
        <div class="feed-post-header">
            <img src="{{ post.profile.profile_image_url }}" alt="{{ post.profile.username }}'s picture">
            <a href="{% url 'profile' post.profile.pk %}">
                <strong>@{{ post.profile.username }}</strong>
            </a>
            <span class="feed-display-name">{{ post.profile.display_name }}</span>
        </div>

        <!-- First photo -->
        <div class="feed-post-photo">
            {% with photos=post.get_all_photos %}
                {% if photos %}
                    <a href="{% url 'post' post.pk %}">
                        <img src="{{ photos.first.get_image_url }}" alt="Post photo">
                    </a>
                {% else %}
                    <a href="{% url 'post' post.pk %}">
                        <img src="https://png.pngtree.com/png-vector/20221125/ourmid/pngtree-no-image-available-icon-flatvector-illustration-thumbnail-graphic-illustration-vector-png-image_40966590.jpg"
                        alt="No image available">
                    </a>
                {% endif %}
            {% endwith %}
        </div>

        <!-- Likes and caption -->
        <div class="feed-post-info">
            <div class="like-count">{{ post.get_likes.count }} likes</div>
            <p class="post-caption"><b>@{{ post.profile.username }}: </b>{{ post.caption }}</p>
            <small class="post-timestamp">{{ post.timestamp }}</small>
        </div>

        <!-- Comments -->
        <div class="feed-post-comments">
            {% for comment in post.get_all_comments %}
                <div class="comment-item">
                    <p><b>@{{ comment.profile.username }}</b> {{ comment.text }}</p>
                </div>
            {% empty %}
                <p class="no-comments">No comments yet.</p>
            {% endfor %}
        </div>

    </div>
    {% empty %}
        <p class="feed-empty">No posts in your feed yet. Follow some profiles to see their posts!</p>
    {% endfor %}

</div>

{% endblock %}

mini_insta/templates/mini_insta/update_post_form.html
<!-- 
File: update_post_form.html
Author: Jocelyn Chan (jchan042@bu.edu) 3/01/2026
Description: The page to update a post's caption
-->

{% extends 'mini_insta/base.html' %}

{% block content %}

<h2>Update @{{ profile.username }}'s Post</h2>

<div class="post-detail-container">

    <!-- Show the post photos -->
    <div class="post-left">
        <div class="post-photos">
            {% for photo in post.get_all_photos %}
                <img src="{{ photo.get_image_url }}" alt="Post photo">
            {% empty %}
                <img src="https://png.pngtree.com/png-vector/20221125/ourmid/pngtree-no-image-available-icon-flatvector-illustration-thumbnail-graphic-illustration-vector-png-image_40966590.jpg"
                alt="No image available">
            {% endfor %}
        </div>
    </div>

    <div class="post-right">

        <!-- Update caption form -->
        <form action="{% url 'update_post' post.pk %}" method="POST">
            {% csrf_token %}

            <div class="form-field">
                <label for="id_caption"><strong>Caption</strong></label>
                {{ form.caption }}
            </div>

            <div class="form-buttons">
                <input type="submit" value="Save">
                <a href="{% url 'post' post.pk %}">
                    <button type="button">Cancel</button>
                </a>
            </div>
        </form>

    </div>
</div>

{% endblock %}

mini_insta/templates/mini_insta/update_profile_form.html
<!-- 
File: update_profile_form.html
Author: Jocelyn Chan (jchan042@bu.edu) 2/26/2026
Description: Form to update a profile 
 -->

{% extends 'mini_insta/base.html' %}

{% block content %}

<h2>Update profile for @{{ profile.username }}</h2>

<div class="form-container">
    <form action="{% url 'update' profile.pk %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <!-- Update display name -->
        <div class="form-field">
            <label for="id_display_name"><strong>Display Name</strong></label>
            {{ form.display_name }}
        </div>

        <!-- Update bio -->
        <div class="form-field">
            <label for="id_bio_text"><strong>Bio</strong></label>
            {{ form.bio_text }}
        </div>

        <!-- Update profile image URL -->
        <div class="form-field">
            <label for="id_profile_image_url"><strong>Profile Image URL</strong></label>
            {{ form.profile_image_url }}
        </div>

        <!-- Buttons -->
        <div class="form-buttons">
            <input type="submit" value="Save Changes">
            <a href="{% url 'profile' profile.pk %}">
                <button type="button">Cancel</button>
            </a>
        </div>

    </form>
</div>

{% endblock %}

<!-- Image URL field -->
        <!-- <div class="form-field">
            <label for="image_url">Image URL:</label>
            <input type="url" name="image_url" id="image_url" placeholder="Paste an image URL here">
        </div> -->